apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tf-helm-app1
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: tf-test-1
    server: 'https://5F91010DF6246621B3275CF388EDA58F.gr7.us-east-1.eks.amazonaws.com'
  source:
    path: dev
    repoURL: 'https://github.com/thomasfischl/argo-demo.git'
    targetRevision: HEAD
  project: thomas-fischl
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
